################################################################################
# [miraâ€”v1.0.1] may i reflect again?
# global (default!) configuration file.
################################################################################
mira:
  file_paths:
    world_repository: "/home/prj/minecraft/repo"
webstats:
  enable: true
  action: "www.somescript.com/dothis.php"
  secret: "abcdef12345"
  position: 0
settings:
  maps_repo: "/home/founders/repo/maps"
  duration:
    vote: 30
    pre_game: 25
    post_game: 25
database:
  enabled: true
  username: "jj"
  password: ""
  database: "mira"
  hostname: ""
  port: 5432